/*
This file will test if its possible to send a file pointer to CUDA and then extract the GRIB 2 file using 
an object generated by ECCODES that will indicate where to find the values 


*/



#include <iostream>
#include <stdlib.h>
#include "eccodes.h"
// #include <cuda_runtime.h>
#include <vector>
#include <string>

// personal functions
#include "decompress_grib_test.h"
#include "shared_test_objs.h"

#define MAX_NUM_STRINGS 100
#define MAX_STRING_LENGTH 100
#define numParams 3


const char * grib_file_path = "/media/kaleb/extraSpace/wrf/";
const char * output_file_path = "/home/kaleb/Desktop/cuda_4-3/";
std::vector<std::string> vctrDate = {"2020", "01", "01"};
codes_index* gr_idx_obj;
char shortnames[MAX_NUM_STRINGS][MAX_STRING_LENGTH]= {"2t", "u", "v"};
long passed_levels[numParams] = {2, 1000, 1000};
int param_indexes[numParams][numParams] = {{-1, -1, -1},
                                           {-1, -1, -1},
                                           {-1, -1, -1}};

int numStations;

void build_index_obj(station_t*);


int main() {

    station_t st_1;
    station_t st_2;
    st_1.lat = 30.2241;
    st_1.lon = 272.0198;

    st_2.lat = 29.7958;
    st_2.lon = 270.8229;

    station_t * stationArr = new station_t[2];
    numStations = 2;
    stationArr[0] = st_1;
    stationArr[1] = st_2;

    /*
    std::cout << "BEFORE" << std::endl;
    for (int i=0; i<numStations; i++) {
        station_t st = stationArr[i];
        std::cout << "CL PT for st " << i << ": " << st.closestPoint << std::endl;
    }

    // stationArr = extract_indexes(stationArr);
    std::cout << "\nAFTER" << std::endl;
    for (int i=0; i<numStations; i++) {
        station_t st = stationArr[i];
        std::cout << "CL PT for st " << i << ": " << st.closestPoint << std::endl;
    }
    */

    // build the grib_index object
    build_index_obj(stationArr);


    codes_index_delete(gr_idx_obj);
    delete [] stationArr;

    return 0;
}

void build_index_obj (station_t* stationArr) {
    codes_handle* h    = NULL;
    gr_idx_obj = NULL;
    long *steps, *levels, *numbers; /* arrays */
    char** shortName = NULL;
    int i, j, k, l;
    size_t stepSize, levelSize, shortNameSize, numberSize;
    long ostep, olevel, onumber;
    char oshortName[200];
    size_t lenshortName = 200;
    int ret = 0, count = 0, err = 0, missing = 0;
    long num_points = 0;
    FILE* f;

    // if (argc != 2) usage(argv[0]);
    //infile = argv[1];

    printf("finding the nearest points for the stations...\n");
    std::string full_path = grib_file_path + vctrDate.at(0) + "/" + vctrDate.at(0) + \
                            vctrDate.at(1) + vctrDate.at(2) + "/" + "hrrr."  + vctrDate.at(0) + \
                            vctrDate.at(1) + vctrDate.at(2) + ".00.00.grib2";
    try {
        f = fopen(full_path.c_str(), "rb");
        if (!f) throw(full_path);
    } catch (std::string full_path) {
        std::cout << "could not open file" << std::endl;
        return;
    }

    double* grib_lats, *grib_lons, *gr_vals;
    codes_handle * idx_h = codes_handle_new_from_file(0, f, PRODUCT_GRIB, &err);

    if (!idx_h || err != 0) {
        std::cout << "could not make handle" << std::endl;
        return;
    }
    CODES_CHECK(codes_get_long(idx_h, "numberOfPoints", &num_points), 0);
    CODES_CHECK(codes_set_double(idx_h, "missingValue", missing), 0);

    grib_lats = (double*)malloc(num_points * sizeof(double));
    if(!grib_lats){
        fprintf(stderr, "Error: unable to allocate %ld bytes\n", (long)(num_points * sizeof(double)));
        exit(0);
    }
    grib_lons = (double*)malloc(num_points * sizeof(double));
    if (!grib_lons){
        fprintf(stderr, "Error: unable to allocate %ld bytes\n", (long)(num_points * sizeof(double)));
        std::free(grib_lats);
        exit(0);
    }
    gr_vals = (double*)malloc(num_points * sizeof(double));
    if(!gr_vals){
        fprintf(stderr, "Error: unable to allocate %ld bytes\n", (long)(num_points * sizeof(double)));
        std::free(grib_lats);
        std::free(grib_lons);
        exit(0);
    }
    CODES_CHECK(codes_grib_get_data(idx_h, grib_lats, grib_lons, gr_vals), 0);

    stationArr = extract_indexes(stationArr, grib_lats, grib_lons, numStations, num_points);

    std::free(grib_lats);
    std::free(grib_lons);
    std::free(gr_vals);
    fclose(f);

    printf("The nearest points for the stations are: \n");
    for (int i=0; i<numStations; i++) {
        int closestPt = stationArr[i].closestPoint;
        printf("Station %d's closest point: %d\n", i, closestPt);

    }


    printf("building the index obj...\n");

    /* create an index given set of keys*/
    gr_idx_obj = codes_index_new(0, "shortName,level,step", &ret);
    if (ret) {
        fprintf(stderr, "Error: %s\n", codes_get_error_message(ret));
        exit(ret);
    }

    /* indexes a file */
    ret = codes_index_add_file(gr_idx_obj, full_path.c_str());
    if (ret) {
        fprintf(stderr, "Error: %s\n", codes_get_error_message(ret));
        exit(ret);
    }
    printf("end indexing...\n");

    /* get the number of distinct values of "step" in the index */
    CODES_CHECK(codes_index_get_size(gr_idx_obj, "step", &stepSize), 0);
    steps = (long*)malloc(sizeof(long) * stepSize);
    if (!steps) exit(1);

    /* get the list of distinct steps from the index */
    /* the list is in ascending order */
    CODES_CHECK(codes_index_get_long(gr_idx_obj, "step", steps, &stepSize), 0);
    printf("stepSize=%ld\n", (long)stepSize);
    for (i = 0; i < stepSize; i++)
        printf("%ld ", steps[i]);
    printf("\n");

    /*same as for "step"*/
    CODES_CHECK(codes_index_get_size(gr_idx_obj, "level", &levelSize), 0);
    levels = (long*)malloc(sizeof(long) * levelSize);
    if (!levels) exit(1);

    /*same as for "step"*/
    CODES_CHECK(codes_index_get_long(gr_idx_obj, "level", levels, &levelSize), 0);
    printf("levelSize=%ld\n", (long)levelSize);
    for (i = 0; i < levelSize; i++)
        printf("%ld ", levels[i]);
    printf("\n");

    CODES_CHECK(codes_index_get_size(gr_idx_obj, "shortName", &shortNameSize), 0);
    shortName = (char**)malloc(sizeof(char*) * shortNameSize);
    if (!shortName) exit(1);
    /*same as for "step"*/
    CODES_CHECK(codes_index_get_string(gr_idx_obj, "shortName", shortName, &shortNameSize), 0);
    printf("shortNameSize=%ld\n", (long)shortNameSize);
    for (i = 0; i < shortNameSize; i++)
        printf("%s ", shortName[i]);
    printf("\n");

    count = 0;
    /* nested loops on the keys values of the index */
    /* different order of the nested loops doesn't affect performance*/
    for (i = 0; i < shortNameSize; i++) {
        /* select the GRIB with shortName=shortName[i] */
        codes_index_select_string(gr_idx_obj, "shortName", shortName[i]);

        for (l = 0; l < levelSize; l++) {
            /* select the GRIB with level=levels[l] */
            codes_index_select_long(gr_idx_obj, "level", levels[l]);

            // for (j = 0; j < numberSize; j++) {
            //     /* select the GRIB with number=numbers[j] */
            //     codes_index_select_long(index, "number", numbers[j]);

            for (k = 0; k < stepSize; k++) {
                /* select the GRIB with step=steps[k] */
                codes_index_select_long(gr_idx_obj, "step", steps[k]);

                /* create a new codes_handle from the index with the constraints
                    imposed by the select statements. It is a loop because
                    in the index there could be more than one GRIB with those
                    constraints */
                while ((h = codes_handle_new_from_index(gr_idx_obj, &ret)) != NULL) {
                    count++;
                    if (ret) {
                        fprintf(stderr, "Error: %s\n", codes_get_error_message(ret));
                        exit(ret);
                    }
                    lenshortName = 200;
                    codes_get_string(h, "shortName", oshortName, &lenshortName);
                    codes_get_long(h, "level", &olevel);
                    // codes_get_long(h, "number", &onumber);
                    codes_get_long(h, "step", &ostep);
                    // printf("shortName=%s ", oshortName);
                    // printf("level=%ld ", olevel);
                    // // printf("number=%ld ", onumber);
                    // printf("step=%ld \n", ostep);

                    // for each element of the array
                        // if the shortnames match and the levels match
                            // store it in the paramIdxes array 
                            // print it out
                    for (int j=0; j<numParams; j++) {
                        long currLevel = passed_levels[j];
                        char currShortname[MAX_STRING_LENGTH];
                        strncpy(currShortname, shortName[j], MAX_STRING_LENGTH);
                        int result = strcmp(oshortName, currShortname);
                        if (result == 0 && currLevel == olevel) {
                            printf("\nShortname: %s was found at shortnameidx: %d\n", currShortname, i);
                            printf("and at levelIdx: %d\n", l);
                        }
                    }


                    codes_handle_delete(h);
                }
                if (ret && ret != GRIB_END_OF_INDEX) {
                    fprintf(stderr, "Error: %s\n", codes_get_error_message(ret));
                    exit(ret);
                }
            }
            
        }
    }
    printf("  %d messages selected\n", count);
}


